[workspace]
members = ["vcs-cli", "vcs-core", "vcs-core/crypto-hash-derive"]
resolver = "3"

[workspace.dependencies]
aws-lc-rs = "1.17.0"
blake3 = { version = "1.8.5", features = ["serde"] }
cfg-if = "1.0.4"
dashmap = { version = "6.1.0", features = ["serde"] }
futures = "0.3.32"
tokio = { version = "1.52.3", features = ["fs", "macros", "rt", "rt-multi-thread", "sync"] }
vcs-core = { path = "vcs-core" }
