[package]
name = "vcs-core"
version = "0.1.0"
edition = "2024"

[dependencies]
aws-lc-rs = { workspace = true }
blake3 = { workspace = true }
crypto-hash-derive = { path = "crypto-hash-derive" }
dashmap = { workspace = true }
bytes = "1.11.1"
elsa = "1.11.2"
serde = "1.0.228"
thiserror = "2.0.18"
tokio = { workspace = true, features = ["macros", "sync"] }
bytemuck = { version = "1.25.0", features = ["must_cast"] }
futures = { version = "0.3.32", default-features = false, features = ["alloc"] }

[dev-dependencies]
lazy_static = "1.5.0"
tokio = { workspace = true, features = ["macros", "rt", "sync"] }
vcs-storage-impl = { path = "../vcs-storage-impl" }
