[package]
name = "vcs-storage-impl"
version = "0.1.0"
edition = "2024"

[dependencies]
blake3 = { workspace = true }
cfg-if = { workspace = true }
dashmap = { workspace = true }
futures = { workspace = true }
hex = "0.4"
postcard = { version = "1", features = ["alloc"] }
serde = "1.0.228"
tokio = { workspace = true }
vcs-core = { workspace = true }
