name: CI

on:
  push:
    branches: [main]
  pull_request:

env:
  RUSTFLAGS: >-
    -A unused_variables
    -A unused_mut
    -A unused_macros
    -A dead_code
    -A unreachable_code
    -A unreachable_patterns
    -D warnings

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        rust: [stable]

    steps:
      - uses: actions/checkout@v6

      - name: Install Rust (${{ matrix.rust }})
        uses: actions-rust-lang/setup-rust-toolchain@v1.15.2
        with:
          toolchain: ${{ matrix.rust }}
          components: rustfmt, clippy

      - name: Cache Cargo
        uses: Swatinem/rust-cache@v2

      - name: Check
        run: cargo check --workspace --all-targets --all-features

      - name: Tests
        run: cargo test --workspace --all-targets --all-features --verbose

      - name: Rustfmt
        run: cargo fmt --all -- --check

      - name: Linting
        run: >
          cargo clippy --workspace --all-targets --all-features --
          -A unused_variables
          -A unused_mut
          -A unused_macros
          -A dead_code
          -A unreachable_code
          -A unreachable_patterns
          -D warnings

      - name: Documentation
        run: RUSTDOCFLAGS="-D warnings" cargo doc --workspace --no-deps --all-features
